CollectMeCompanionInfo = {
  [62514] = "Not available on live servers",  -- Alarming Clockbot
  [10685] = "Sold by Magus Tirth in Thousand Needles for 1G",  -- Ancona Chicken
  [10696] = "Dropped by Draconic Magelord, Blue Scalebane, Draconic Mageweaver and Blue Dragonspawn in Azshara",  -- Azure Whelpling
  [61855] = "Obtained by getting online during the 4th anniversary of World of Warcraft",  -- Baby Blizzard Bear
  [10714] = "Sold by Xan'tish in Orgrimmar for 50S",  -- Black Kingsnake
  [10675] = "Dropped by Dalaran Spellscribe 20% or very rare from Dalaran Mobs in Silverpine Forrest at Ambermill",  -- Black Tabby Cat
  [36031] = "Sold by Dealer Rashaad in Netherstorm for 10G",  -- Blue Dragonhawk Hatchling
  [35907] = "Sold by Sixx in the Exodar for 50S",  -- Blue Moth
  [10673] = "Sold by Donni Anthania in Elwynn Forrest for 40S",  -- Bombay Cat
  [10709] = "Sold by Halpa in Thunder Bluff for 40S",  -- Brown Prairie Dog
  [35239] = "Sold by Dealer Rashaad in Netherstorm for 10G",  -- Brown Rabbit
  [10716] = "Sold by Xan'tish in Orgrimmar for 50S",  -- Brown Snake
  [46426] = "Contained in Bag of Fishing Treasures which is a reward from the Outland fishing daily quest Crocolisks in the City started by Old Man Barlo in Terokkar Forest",  -- Chuck
  [61351] = "Contained in Cracked Egg which spawns from Mysterious Egg which can be bought from Geen in Sholazar Basin with a The Oracles reputation of at least revered",  -- Cobra Hatchling
  [10680] = "Sold by Narkk in Stranglethorn Vale for 40S",  -- Cockatiel
  [10688] = "Sold by Jeremiah Payson in Undercity or Dealer Rashaad in Netherstorm for 50S",  -- Cockroach
  [10674] = "Sold by Donni Anthania in Elwynn Forest for 40S",  -- Cornish Rex Cat
  [10717] = "Sold by Xan'tish in Orgrimmar or Dealer Rashaad in Netherstorm for 50S",  -- Crimson Snake
  [10697] = "Dropped by Flamesnorting Whelp, Crimson Whelp or Red Whelp in the Wetlands",  -- Crimson Whelpling
  [10695] = "Dropped by Searing Whelp in Dustwallow Marsh or Scalding Whelp in the Badlands",  -- Dark Whelpling
  [25162] = "Contained in Oozing Bag which is dropped by most of ooze and slime mobs in the WOW Classic high level zones",  -- Disgusting Oozeling
  [40614] = "Reward from the Outland Children's Week questline",  -- Egbert
  [10698] = "Dropped by Dreaming Whelp and Adolescent Whelp in the Swamp of Sorrows",  -- Emerald Whelpling
  [26533] = "Contained in the presents under the christmas trees during Winter Veil",  -- Father Winter's Helper
  [36034] = "Dropped by Bogflare Needler in Zangamarsh",  -- Firefly
  [53316] = "Sold by Darahir in the Dalaran Sewers for 40G",  -- Ghostly Skull
  [59250] = "Can be fished in the Dalaran Sewers",  -- Giant Sewer Rat
  [36027] = "Sold by Jilanne in Eversong Woods for 50S",  -- Golden Dragonhawk Hatchling
  [10707] = "Sold by Shylenai in Darnassus for 50S",  -- Great Horned Owl
  [10683] = "Dropped by Defias Pirate in the Deadmines",  -- Green Wing Macaw
  [10706] = "Sold by Shylenai in Darnassus for 50S",  -- Hawk Owl
  [10682] = "Dropped by Bloodsail Mobs in Strangethorn (very very rare)",  -- Hyacinth Macaw
  [23811] = "Reward from Quest Spawn of Jubjub stared by Morja at Darkmoon Faire",  -- Jubling
  [61472] = "Obtained in the secret room in Dalaran where you can enter after completing the Higher Learning Achievment",  -- Kirin Tor Familiar
  [19772] = "Can be built by engineers",  -- Lifelike Toad
  [61991] = "Reward for the Lil' Game Hunter Achievment (collect 75 companions)",  -- Little Fawn
  [33050] = "One of the wishes from Mr Pinchy which can be fished from the pools in Skettis",  -- Magical Crawdad
  [35156] = "Sold by Dealer Rashaad in Netherstorm for 40G",  -- Mana Wyrmling
  [12243] = "Reward when you complete the 3 OOX Quests in Feralas, Tanaris and Hinterlands",  -- Mechanical Chicken
  [4055]  = "Built by an engineer",   -- Mechanical Squirrel
  [39181] = "Reward for the quest Skywing started by Skywing in Terokkar Forest",  -- Miniwing
  [43918] = "Obtained by using Hex Sticks on the frogs in Zul Aman",  -- Mojo
  [28739] = "Reward for the Stormwind or Orgrimmar Children's Week questline",  -- Mr. Wiggles
  [43698] = "Contained in Bag of Fishing Treasures which is a reward from the Outland fishing daily quest Crocolisks in the City started by Old Man Barlo in Terokkar Forest",  -- Muckbreath
  [51716] = "Sold by Grella in Skettis for 40G. You need to be exalted with the Sha'Tari Skyguard",  -- Nether Ray Fry
  [10676] = "Sold by Donni Anthania in Elwynn Forest for 40S",  -- Orange Tabby Cat
  [40634] = "Reward from the Outland Children's Week questline",  -- Peanut
  [27570] = "Contained in the Gifts of Adoration from the Love is in the Air festival",  -- Peddlefeet
  [61357] = "Sold by Sairuk in Dragonblight or Tanaika in Howling Fjord for 12G. You need to be exalted with the Kalu'ak",  -- Pengu
  [46599] = "Dropped by Kael'thas Sunstrider in Magister's Terrace",  -- Phoenix Hatchling
  [61350] = "Contained in Cracked Egg which spawns from Mysterious Egg which can be bought from Geen in Sholazar Basin with a The Oracles reputation of at least revered",  -- Proto-Drake Whelp
  [36028] = "Sold by Jilanne in Eversong Woods for 50S",  -- Red Dragonhawk Hatchling
  [35909] = "Sold by Dealer Rashaad in Netherstorm for 10G",  -- Red Moth
  [45890] = "Contained in Ice Chest which is dropped by Ahune in the Slave Pens during the Midsummer Festival",  -- Scorchling
  [10684] = "Sold by Narkk in Stranglethorn Vale or Dealer Rashaad in Netherstorm for 40S",  -- Senegal
  [10677] = "Dropped by Cookie in the Deadmines or sold by Dealer Rashaad in Netherstorm for 60S",  -- Siamese Cat
  [36029] = "Sold by Jilanne in Eversong Woods for 50S",  -- Silver Dragonhawk Hatchling
  [10678] = "Sold by Donni Anthania in Elwynn Forest for 40S",  -- Silver Tabby Cat
  [42609] = "Dropped by the Headless Horseman and contained in Crudely Wrapped Gift and Treat Bag during Hallow's End",  -- Sinister Squashling
  [16450] = "Reward for the quest En-Ay-Es-Tee-Why stared by Kibler in the Burning Steppes",  -- Smolderweb Hatchling
  [46425] = "Contained in Bag of Fishing Treasures which is a reward from the Outland fishing daily quest Crocolisks in the City started by Old Man Barlo in Terokkar Forest",  -- Snarly
  [10711] = "Sold by Yarlyn Amberstill in Dun Morogh for 20S",  -- Snowshoe Rabbit
  [28738] = "Reward for the Stormwind or Orgrimmar Children's Week questline",  -- Speedy
  [28871] = "Sold by Midsummer Supplier and Midsummer Merchant in the capital cities for 350 Burning Blossoms during the Midsummer's Festival",  -- Spirit of Summer
  [40990] = "Reward for the Shop Smart, Shop Pet...Smart Achievment (collect 50 companions)",  -- Stinker
  [61348] = "Contained in Cracked Egg which spawns from Mysterious Egg which can be bought from Geen in Sholazar Basin with a The Oracles reputation of at least revered",  -- Tickbird Hatchling
  [45082] = "Sold by Mycah in Zangamarsh for 30 Glowcaps. You need to be exalted with Sporeggar",  -- Tiny Sporebat
  [26045] = "Contained in Gaily Wrapped Present during Winter's Veil",  -- Tiny Snowman
  [43697] = "Contained in Bag of Fishing Treasures which is a reward from the Outland fishing daily quest Crocolisks in the City started by Old Man Barlo in Terokkar Forest",  -- Toothy
  [26010] = "Built by an engineer",  -- Tranquil Mechanical Yeti
  [10704] = "Sold by Flik on Darkmoon Faire for 1G",  -- Tree Frog
  [13548] = "Reward for Quest CLUCK! started by Chickens in Westfall after you /chicken to them for a while",  -- Westfall Chicken
  [28740] = "Reward for the Stormwind or Orgrimmar Children's Week questline",  -- Whiskers the Rat
  [10679] = "Sold by Lil Timmy in Stormwind for 1G (Limited Supply)",  -- White Kitten
  [35911] = "Sold by Sixx in the Exodar for 50S",  -- White Moth
  [61349] = "Contained in Cracked Egg which spawns from Mysterious Egg which can be bought from Geen in Sholazar Basin with a The Oracles reputation of at least revered",  -- White Tickbird Hatchling
  [40613] = "Reward from the Outland Children's Week questline",  -- Willy
  [26529] = "Contained in Gaily Wrapped Present during Winter's Veil",  -- Winter Reindeer
  [26541] = "Contained in Gaily Wrapped Present during Winter's Veil",  -- Winter's Little Helper
  [39709] = "Soly by Larkin Thunderbrew in Ironforge and Ray'ma in Orgrimmar for 50S",  -- Wolpertinger
  [10703] = "Sold by Flik on Darkmoon Faire for 1G (Limited Supply)",  -- Wood Frog
  [15999] = "Reward for the quest Kibler's Exotic Pets stared by Kibler in the Burning Steppes",  -- Worg Pup
  [35910] = "Sold by Sixx in the Exodar for 50S",  -- Yellow Moth
  [40549] = "Obtained from a lootcard of the WoW Trading Card Game: Through the Dark Portal",  -- Bananas
  [54187] = "Contained in Gaily Wrapped Present during Winter's Veil 2007",  -- Clockwork Rocket Bot
  [45127] = "Obtained from a lootcard of the WoW Trading Card Game: March of the Legion",  -- Dragon Kite
  [48408] = "Obtained by winning a battleground during Beijing 2008 Summer Olympics",  -- Essence of Competition
  [49964] = "Obtained from a lootcard of the WoW Trading Card Game: Hunt for Illidan",  -- Ethereal Soul-Trader
  [52615] = "Included in the WotLK Collectors Edition",  -- Frosty
  [45174] = "Gift for attendess of the 2007 Blizzard Worldwide Invitational",  -- Golden Pig
  [27241] = "Offered as a fan websites gift around Christmas 2006 in Europe.",  -- Gurky
  [30156] = "Obtained from a lootcard of the WoW Trading Card Game: Heroes of Azeroth",  -- Hippogryph Hatchling
  [40405] = "Gift for attendess of the 2007 Blizzard Worldwide Invitational, Chinese and Korean servers only",  -- Lucky
  [24988] = "Included in the Burning Crusade Collectors Edition",  -- Lurky
  [17708] = "Included in the WoW Classic Collectors Edition",  -- Mini Diablo
  [53082] = "Gift for attendess of the 2008 Blizzard Worldwide Invitational",  -- Mini Tyrael
  [24696] = "Gift for attendees of the 2005 Blizzcon",  -- Murky
  [32298] = "Included in the Burning Crusade Collectors Edition",  -- Netherwhelp
  [17707] = "Included in the WoW Classic Collectors Edition",  -- Panda Cub
  [28505] = "Obtained by a Coca Cola event in China only",  -- Poley
  [45125] = "Obtained from a lootcard of the WoW Trading Card Game: March of the Legion",  -- Rocket Chicken
  [45175] = "Only on Chinese realms",  -- Silver Pig
  [48406] = "Obtained by winning a battleground during Beijing 2008 Summer Olympics",  -- Spirit of Competition
  [23531] = "Special promotion only on Chinese realms",  -- Tiny Green Dragon
  [23530] = "Special promotion only on Chinese realms",  -- Tiny Red Dragon
  [51851] = "Dropped by Prince Tenris Mirkblood in Karazhan on the pre WotLK Event",  -- Vampiric Batling
  [17709] = "Included in the WoW Classic Collectors Edition",  -- Zergling
  [15067] = "Obtained by Freedom for All Creatures Quest started by Kindal Moonweaver in Feralas and dropped by Sprite Darters in Feralas",  -- Sprite Darter Hatchling
  [15049] = "Crafted by Engineers. Bind on pickup schematic drops in Gnomeregan from Arcane Nullifier X-21, Crowd Pummeler 9-60, Peacekeeper Security Suit. Pet now BOE",  -- Lil' Smoky
  [15048] = "Crafted by Engineers. Bind on pickup schematic drops in Gnomeregan from Mekgineer Thermaplugg. Pet now BOE",  -- Pet Bombling
  [62562] = "Sold by Irisee (Exodar Quartermaster) at the Argent Tournament for 40 Champion's Seals. You must be a Draenei or a Champion of the Exodar",  -- Ammen Vale Lashling
  [62508] = "Sold by Derrick Brindlebeard (Ironforge Quartermaster) at the Argent Tournament for 40 Champion's Seals. You must be a Dwarf or a Champion of Ironforge",  -- Dun Morogh Cub
  [62513] = "Sold by Freka Bloodaxe (Orgrimmar Quartermaster) at the Argent Tournament for 40 Champion's Seals. You must be an Orc or a Champion of Orgrimmar",  -- Durotar Scorpion
  [62516] = "Sold by Corporal Arthur Flew (Stormwind Quartermaster) at the Argent Tournament for 40 Champion's Seals. You must be a Human or a Champion of Stormwind",  -- Elwyn Lamb
  [62564] = "Sold by Trellis Morningsun (Silvermoon Quartermaster) at the Argent Tournament for 40 Champion's Seals. You must be a Blood Elve or a Champion of Silvermoon",  -- Enchanted Broom
  [62491] = "Sold by Rook Hawkfist (Darnassus Quartermaster) at the Argent Tournament for 40 Champion's Seals. You must be a Night Elve or a Champion of Darnassus",  -- Teldrassid Sproutling
  [62510] = "Sold by Eliza Killian (Undercity Quartermaster) at the Argent Tournament for 40 Champion's Seals. You must be an Undead or a Champion of the Undercity",  -- Tirisfal Batling
  [62674] = "Sold by Rillie Spindlenut (Gnomeregan Quartermaster) at the Argent Tournament for 40 Champion's Seals. You must be a Gnome or a Champion of Gnomeregan",  -- Mechanopeep
  [62542] = "Sold by Doru Thunderhorn (Thunder Bluff Quartermaster) at the Argent Tournament for 40 Champion's Seals. You must be a Tauren or a Champion of Thunder Bluff",  -- Mulgore Hatchling
  [63712] = "Sold by Samamba (Sen'Jin Quartermaster) at the Argent Tournament for 40 Champion's Seals. You must be a Troll (ingame, not on forums) or a Champion of Sen'Jin",  -- Sen'Jin Fetish
  [63318] = "Obtained by playing 200 arena matches on the arena tournament server",  -- Murkimus the Gladiator
  [62561] = "Contained in the Bag of Fishing Treasures which is a reward from the Northrend Fishing daily quests",  -- Strand Crawler
  [61725] = "Can be bought for 100 Chocolate Eggs or random drop in an Egg on the Noblegarden festival",  -- Spring Rabbit
  [62609] = "Obtained by becoming a champion on the Argent Tournament",  -- Argent Squire
  [62746] = "Obtained by becoming a champion on the Argent Tournament",  -- Argent Gruntling
  [65682] = "Special promotion from the www.mountaindewgamefuel.com with a valid battle.net account, available from May 15 - Aug. 20, 2009. US servers only.", -- Warbot
  [65381] = "Obtained from Dalaran Children's Week quest, You may only choose either Curious Oracle Hatchling or Curious Wolvar Pup",  -- Curious Oracle Hatchling
  [65382] = "Obtained from Dalaran Children's Week quest, You may only choose either Curious Oracle Hatchling or Curious Wolvar Pup",  -- Curious Wolvar Pup
  [66096] = "Obtained from Silver Covenant or Sunreavers Quartermaster for 40 Champion seals. Must be exaulted with Silver Covenant or Sunreavers.", -- Shimmering Wyrmling
  [67413] = "Dropped by rare spawn Dart in Dustwallow Marsh",  -- Darting Hatchling
  [67414] = "Drops in Wailing Caverns from Deviate Guardian and Deviate Ravager",  -- Deviate Hatchling
  [67415] = "Drops in Zul'Drak from Gundrak Raptor",  -- Gundrak Hatchling
  [67416] = "Dropped by rare spawn Takk the Leaper in The Barrens",  -- Leaping Hatching
  [67417] = "Sold by vendor Breanni in Dalaran",  -- Obsidian Hatchling
  [67418] = "Drops from rare spawn Ravasaur Matriarch in Un'goro",  -- Ravasaur Hatchling
  [67419] = "Dropped by rare spawn Razormaw Matriarch in Wetlands",  -- Razormaw Hatchling
  [67420] = "Dropped by Razzashi Raptor in Zul'Gurub",  -- Razzashi Hatchling
  [66030] = "Free gift for US and EU attendees of BlizzCon 2009 or buying PVP coverage of BlizzCon 2009",  -- Grunty
  [61773] = "Obtained after getting the Pilgrim Achievement",  -- Plump Turkey
  [44369] = "Sold by Brewfest vendors for 100 Brewfest Prize Tokens",  -- Pint-Sized Pink Pachyderm
  [69677] = "Purchased from Blizzard's online store, Bind On Account",  -- Lil' K.T.
  [69452] = "Given to players who have an active Blizzard Authenticator linked to their account",  -- Core Hound Pup
  [69535] = "Blizzard Online Store Pet, included when purchasing the Gryphon Hatchling Stuffed Animal",  -- Gryphon Hatchling
  [69536] = "Blizzard Online Store Pet, included when purchasing the Wind Rider Cub Stuffed Animal",  -- Wind Rider Cub
  [69539] = "N/A ",  -- Zipao Tiger
  [69541] = "Purchased from Blizzard's online store, Bind On Account",  -- Pandaren Monk
  [68810] = "Redeemed from TCG loot code",  -- Spectral Tiger Cub
  [68767] = "Redeemed from TCG loot code",  -- Tuskarr Kite
  [69002] = "Reward for being online during the World of Warcraft 5th anniversary",  -- Onyxian Whelping
  [55068] = "Gift for merging World of Warcraft account into Battle.net, available on all future characters. Account must be created before offer is removed.",  -- Oswald The Penguin
  [65358] = "Sold by Breanni pet supplies vendor in Dalaran for 50g, patch 3.3", -- Calico Cat
  [10713] = "Sold by Braeanni pet supplies vendor in Dalaran for 50g, patch 3.3",  -- Albino Snake
  [70613] = "Reward for grouping with 100 random players using the random heroic dungeon group tool introduced in 3.3", -- Perky Pug
  [71840] = "Drops from Apothecary Hummel in Shadowfang Keep during Love is in the Air holiday festival.", -- Toxic Wasteling
  [75134] = "Sold by Jepetto (or his assistant) in Dalaran for 50g, patch 3.33",  -- Blue Clockwork Rocketbot
  [75906] = "Purchased from Blizzard's Online Store, Bind On Account for all present and future characters",  -- Lil' XT
}